### PR TITLE
fixing the build step,, path names changed for deploy and deploy-assets

### PR DESCRIPTION
**Pull request by ahmedBazzara**
i used a relative path in the gulpfile to point at the "build" folder instead of having it as a variable from "server.config.json" which is a static path pointint at "nerush" username ,,// temproary fix.

The rest of the changes with SemanticUI came after i ran "npm install"

### CODE REVIEW

**Comment by flennmark** [comment]
@ahmedBazzara : There is some check here failing. Should we fix this first? Or is it more important to commit this fix?

**Comment by ahmedBazzara** [comment]
we should fix it yeah
i don't understand the problem clearly though

**Comment by flennmark** [comment]
@marols : Any ideas?

**Comment by marols** [comment]
The problem was that CircleCI was activated for the repo and it therefore required a CircleCI config to be available. It was available in the master branch after my merge. To fix the issue I rebased your branch from master, @ahmed-Bazzara.

The build is green now, yay!

**Pull request merged**
